services:
  api:
    container_name: fitme-api
    restart: always
    build: .
    ports:
      - '5000:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo/fitme
      - NODE_ENV=development
  mongo:
    image: mongo
    ports:
      - '27018:27017'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
